version: '2'
services:
    # https://elk-docker.readthedocs.io/
    elk:
        image: sebp/elk
        ports:
            - "5601:5601"  # Kibana
            - "9200:9200"  # Elastic
            - "5044:5044"  # Logstash / Beats

    # https://www.elastic.co/guide/en/apm/server/current/getting-started-apm-server.html
    apm-server:
        image: store/elastic/apm-server:7.17.2
        ports:
            - "8200:8200"  # APM Server
        command: ./apm-server -e -E output.elasticsearch.hosts=elk:9200 -E apm-server.host=0.0.0.0:8200

    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./russky:/usr/src/app/russky
        environment:
            - OTEL_RESOURCE_ATTRIBUTES=service.name=russky-app-2022,service.version=1.0,deployment.environment=dev
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://apm-server:8200
            - ELASTIC_APM_SERVER_ENDPOINT=apm-server:8200

