version: '2'
services:

    app:
        build: .
        image: cr.yandex/crphntksaqh2dho7ale3/russky-app-2022 # registry-yndx-dm-fish2
        ports:
            - "8080:8080"
        volumes:
            - ./russky:/usr/src/app/russky
            - /var/log/russky:/var/log/russky
        env_file:
            - .env.dev
